plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.seleniumhq.selenium:selenium-java:4.33.0'
    implementation 'io.github.bonigarcia:webdrivermanager:6.3.2'

    testImplementation 'io.cucumber:cucumber-java:7.34.4'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.34.4'

    testImplementation 'org.junit.jupiter:junit-jupiter:6.0.3'
    testImplementation 'org.junit.platform:junit-platform-suite:1.12.2'

    implementation 'io.rest-assured:rest-assured:5.5.1'
    implementation 'io.rest-assured:json-schema-validator:5.5.1'

    implementation 'com.networknt:json-schema-validator:3.0.6'
}

test {
    useJUnitPlatform()

    testLogging {
        events "PASSED", "FAILED", "SKIPPED"
        exceptionFormat "full"
    }

    tasks.register("apiTest", Test) {
        useJUnitPlatform()

        systemProperty "cucumber.filter.tags", "@api"
    }

    tasks.register("webTest", Test) {
        useJUnitPlatform()

        systemProperty "cucumber.filter.tags", "@web"
    }
}